# 조건에 맞는 데이터 추출

In [1]:
import pandas as pd

In [3]:
exam = pd.read_csv("./Data/exam.csv")

In [4]:
exam.shape

(20, 5)

In [6]:
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [8]:
exam.describe()

             id     nclass       math    english    science
count  20.00000  20.000000  20.000000  20.000000  20.000000
mean   10.50000   3.000000  57.450000  84.900000  59.450000
std     5.91608   1.450953  20.299015  12.875517  25.292968
min     1.00000   1.000000  20.000000  56.000000  12.000000
25%     5.75000   2.000000  45.750000  78.000000  45.000000
50%    10.50000   3.000000  54.000000  86.500000  62.500000
75%    15.25000   4.000000  75.750000  98.000000  78.000000
max    20.00000   5.000000  90.000000  98.000000  98.000000

In [11]:
exam.query("nclass==1")

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58

In [13]:
exam.query("nclass!=2")

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [14]:
exam.query("nclass <= 2")

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25

# 초과, 미만, 이상, 이하

In [16]:
exam.query("math > 50")

    id  nclass  math  english  science
1    2       1    60       97       60
6    7       2    80       90       45
7    8       2    90       78       25
10  11       3    65       65       65
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [19]:
exam.query("math < 50")

    id  nclass  math  english  science
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
8    9       3    20       98       15
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12

In [21]:
exam.query("nclass == 1 & math >= 50")

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60

In [23]:
exam.query("nclass == 2 & english > 80")

   id  nclass  math  english  science
5   6       2    50       89       98
6   7       2    80       90       45

In [24]:
exam.query("nclass == 2 & english > 60 & math >=40")

   id  nclass  math  english  science
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25

# OR 조건

In [25]:
# 수학 점수가 90점 이상이거나 영어 점수가 90점 이상인 경우
exam.query("math >= 90 | english >= 90")

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
3    4       1    30       98       58
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
12  13       4    46       98       65
15  16       4    58       98       65

In [32]:
# 1, 3, 5반만 추출하자
exam.query("nclass == 1 | nclass == 2 | nclass == 3")

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32

In [39]:
nclass1 = exam.query("nclass == 1")
nclass2 = exam.query("nclass == 2")

In [40]:
nclass2["math"].mean()

np.float64(61.25)

In [35]:
nclass2["english"].sum()

np.int64(337)

In [42]:
tmp = nclass1[["math", "english"]].mean()
type(tmp)

pandas.Series

In [44]:
exam.query("nclass == 1")["nclass", "id", "math"]

KeyError: ('nclass', 'id', 'math')

In [47]:
exam.query("math >= 50")[["id", "math"]].head()

   id  math
0   1    50
1   2    60
5   6    50
6   7    80
7   8    90

In [49]:
exam.query("math >= 50")[["id", "math"]].head(7)

    id  math
0    1    50
1    2    60
5    6    50
6    7    80
7    8    90
9   10    50
10  11    65

In [50]:
type(exam.query("math >= 50")[["math"]])

pandas.DataFrame

In [51]:
exam.query("math >= 50") \
    [["id", "math"]] \
        .head(3)

   id  math
0   1    50
1   2    60
5   6    50

# 정렬

In [54]:
exam.sort_values("math")

    id  nclass  math  english  science
8    9       3    20       98       15
4    5       2    25       80       65
3    4       1    30       98       58
2    3       1    45       86       78
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
0    1       1    50       98       50
9   10       3    50       98       45
5    6       2    50       89       98
15  16       4    58       98       65
1    2       1    60       97       60
10  11       3    65       65       65
16  17       5    65       68       98
14  15       4    75       56       78
19  20       5    78       83       58
17  18       5    80       78       90
6    7       2    80       90       45
18  19       5    89       68       87
7    8       2    90       78       25

In [58]:
exam.sort_values("math", ascending=False)

    id  nclass  math  english  science
7    8       2    90       78       25
18  19       5    89       68       87
6    7       2    80       90       45
17  18       5    80       78       90
19  20       5    78       83       58
14  15       4    75       56       78
10  11       3    65       65       65
16  17       5    65       68       98
1    2       1    60       97       60
15  16       4    58       98       65
0    1       1    50       98       50
5    6       2    50       89       98
9   10       3    50       98       45
13  14       4    48       87       12
12  13       4    46       98       65
2    3       1    45       86       78
11  12       3    45       85       32
3    4       1    30       98       58
4    5       2    25       80       65
8    9       3    20       98       15

In [60]:
exam.sort_values("math", ascending=False).head(3)

    id  nclass  math  english  science
7    8       2    90       78       25
18  19       5    89       68       87
6    7       2    80       90       45

In [62]:
exam.sort_values(["nclass", "math"], ascending=False)

    id  nclass  math  english  science
18  19       5    89       68       87
17  18       5    80       78       90
19  20       5    78       83       58
16  17       5    65       68       98
14  15       4    75       56       78
15  16       4    58       98       65
13  14       4    48       87       12
12  13       4    46       98       65
10  11       3    65       65       65
9   10       3    50       98       45
11  12       3    45       85       32
8    9       3    20       98       15
7    8       2    90       78       25
6    7       2    80       90       45
5    6       2    50       89       98
4    5       2    25       80       65
1    2       1    60       97       60
0    1       1    50       98       50
2    3       1    45       86       78
3    4       1    30       98       58

In [66]:
exam.sort_values(["nclass", "math"], ascending=[True, False])

    id  nclass  math  english  science
1    2       1    60       97       60
0    1       1    50       98       50
2    3       1    45       86       78
3    4       1    30       98       58
7    8       2    90       78       25
6    7       2    80       90       45
5    6       2    50       89       98
4    5       2    25       80       65
10  11       3    65       65       65
9   10       3    50       98       45
11  12       3    45       85       32
8    9       3    20       98       15
14  15       4    75       56       78
15  16       4    58       98       65
13  14       4    48       87       12
12  13       4    46       98       65
18  19       5    89       68       87
17  18       5    80       78       90
19  20       5    78       83       58
16  17       5    65       68       98

# 파생변수 추가

In [68]:
# 합계 컬럼
exam.assign(total = exam["math"] + exam["english"] + exam["science"])

    id  nclass  math  english  science  total
0    1       1    50       98       50    198
1    2       1    60       97       60    217
2    3       1    45       86       78    209
3    4       1    30       98       58    186
4    5       2    25       80       65    170
5    6       2    50       89       98    237
6    7       2    80       90       45    215
7    8       2    90       78       25    193
8    9       3    20       98       15    133
9   10       3    50       98       45    193
10  11       3    65       65       65    195
11  12       3    45       85       32    162
12  13       4    46       98       65    209
13  14       4    48       87       12    147
14  15       4    75       56       78    209
15  16       4    58       98       65    221
16  17       5    65       68       98    231
17  18       5    80       78       90    248
18  19       5    89       68       87    244
19  20       5    78       83       58    219

In [76]:
exam.assign(total = exam["math"] + exam["english"] + exam["science"],
            mean = (exam["math"] + exam["english"] + exam["science"]) / 3)

    id  nclass  math  english  science  total       mean
0    1       1    50       98       50    198  66.000000
1    2       1    60       97       60    217  72.333333
2    3       1    45       86       78    209  69.666667
3    4       1    30       98       58    186  62.000000
4    5       2    25       80       65    170  56.666667
5    6       2    50       89       98    237  79.000000
6    7       2    80       90       45    215  71.666667
7    8       2    90       78       25    193  64.333333
8    9       3    20       98       15    133  44.333333
9   10       3    50       98       45    193  64.333333
10  11       3    65       65       65    195  65.000000
11  12       3    45       85       32    162  54.000000
12  13       4    46       98       65    209  69.666667
13  14       4    48       87       12    147  49.000000
14  15       4    75       56       78    209  69.666667
15  16       4    58       98       65    221  73.666667
16  17       5    65       68       98    231  77.000000
17  18       5    80       78       90    248  82.666667
18  19       5    89       68       87    244  81.333333
19  20       5    78       83       58    219  73.000000

In [77]:
import numpy as np

In [78]:
exam.assign(test = np.where(exam["science"] >= 60, "pass", "fail"))

    id  nclass  math  english  science  test
0    1       1    50       98       50  fail
1    2       1    60       97       60  pass
2    3       1    45       86       78  pass
3    4       1    30       98       58  fail
4    5       2    25       80       65  pass
5    6       2    50       89       98  pass
6    7       2    80       90       45  fail
7    8       2    90       78       25  fail
8    9       3    20       98       15  fail
9   10       3    50       98       45  fail
10  11       3    65       65       65  pass
11  12       3    45       85       32  fail
12  13       4    46       98       65  pass
13  14       4    48       87       12  fail
14  15       4    75       56       78  pass
15  16       4    58       98       65  pass
16  17       5    65       68       98  pass
17  18       5    80       78       90  pass
18  19       5    89       68       87  pass
19  20       5    78       83       58  fail

In [108]:
exam.assign(total = exam["math"] + exam["english"] + exam["science"]) \
    .sort_values(["nclass","total"], ascending=[True, False])

    id  nclass  math  english  science  total
1    2       1    60       97       60    217
2    3       1    45       86       78    209
0    1       1    50       98       50    198
3    4       1    30       98       58    186
5    6       2    50       89       98    237
6    7       2    80       90       45    215
7    8       2    90       78       25    193
4    5       2    25       80       65    170
10  11       3    65       65       65    195
9   10       3    50       98       45    193
11  12       3    45       85       32    162
8    9       3    20       98       15    133
15  16       4    58       98       65    221
12  13       4    46       98       65    209
14  15       4    75       56       78    209
13  14       4    48       87       12    147
17  18       5    80       78       90    248
18  19       5    89       68       87    244
16  17       5    65       68       98    231
19  20       5    78       83       58    219

# 람다식 적용 총합 구하기

In [109]:
def abc(x): 
    return x*1

In [110]:
exam.assign(total = lambda x: x["math"] + x["english"] + x["science"])

    id  nclass  math  english  science  total
0    1       1    50       98       50    198
1    2       1    60       97       60    217
2    3       1    45       86       78    209
3    4       1    30       98       58    186
4    5       2    25       80       65    170
5    6       2    50       89       98    237
6    7       2    80       90       45    215
7    8       2    90       78       25    193
8    9       3    20       98       15    133
9   10       3    50       98       45    193
10  11       3    65       65       65    195
11  12       3    45       85       32    162
12  13       4    46       98       65    209
13  14       4    48       87       12    147
14  15       4    75       56       78    209
15  16       4    58       98       65    221
16  17       5    65       68       98    231
17  18       5    80       78       90    248
18  19       5    89       68       87    244
19  20       5    78       83       58    219

# 요약 통계 구하기

In [111]:
type(exam.agg(mean_math = ("math", "sum")))
exam.agg(mean_math = ("math", "sum"))

           math
mean_math  1149

In [ ]:
#집단별, 그룹별 통계 
exam.groupby("nclass").agg(mean_amth = ("math", "sum"))

        mean_amth
nclass
1             185
2             245
3             180
4             227
5             312

In [113]:
exam \
.groupby("nclass", as_index=False) \
.agg(mean_math = ("math", "mean"), 
    sum_math = ("math", "sum"),
    median_math = ("math", "median"), 
    n = ("nclass", "count")
    )

   nclass  mean_math  sum_math  median_math  n
0       1      46.25       185         47.5  4
1       2      61.25       245         65.0  4
2       3      45.00       180         47.5  4
3       4      56.75       227         53.0  4
4       5      78.00       312         79.0  4

In [114]:
exam.groupby("nclass").mean()

          id   math  english  science
nclass
1        2.5  46.25    94.75    61.50
2        6.5  61.25    84.25    58.25
3       10.5  45.00    86.50    39.25
4       14.5  56.75    84.75    55.00
5       18.5  78.00    74.25    83.25

In [115]:
mpg = pd.read_csv("./Data/mpg.csv")
mpg.shape

(234, 11)

In [116]:
mpg.head(2)

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl category
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact

In [117]:
mpg.groupby("manufacturer").agg(mean_cty = ("cty", "mean")).sort_values("mean_cty", ascending=False).head(5)

               mean_cty
manufacturer
honda         24.444444
volkswagen    20.925926
subaru        19.285714
hyundai       18.642857
toyota        18.529412

In [119]:
mpg.query("manufacturer == 'audi'").groupby(["drv"]).agg(n = ("drv", "count"))

      n
drv
4    11
f     7

In [121]:
mpg["drv"].value_counts()

drv
f    106
4    103
r     25
Name: count, dtype: int64

In [123]:
mpg.query("manufacturer == 'toyota'")["drv"].value_counts()

drv
f    19
4    15
Name: count, dtype: int64

In [124]:
mpg["drv"].value_counts().to_frame('n').query("n > 100")

       n
drv
f    106
4    103

In [126]:
mpg.head()

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl category
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [140]:
#suv 차 종류에 대해서 합산 연비, 제조 회사 별로 분리, 내림차순, top 5만 본다. 
mpg.query("category == 'suv'") \
    .assign(total = (mpg["cty"] + mpg["hwy"]) / 2) \
    .groupby("manufacturer")  \
    .agg(mean_total = ("total", "mean")) \
    .sort_values("mean_total", ascending=False)

              mean_total
manufacturer
subaru         21.916667
toyota         16.312500
nissan         15.875000
mercury        15.625000
jeep           15.562500
ford           15.333333
chevrolet      14.888889
lincoln        14.166667
land rover     14.000000
dodge          13.928571

# 데이터가 흩어져 있다. -> 데이터를 합쳐야 한다.

In [ ]:
#중간고사
test1 = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5], 
        "midterm": [60, 80, 70, 90, 85]
    }
)

In [143]:
#기말고사
test2 = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5], 
        "final": [70, 83, 65, 95, 80]
    }
)

In [145]:
test1

   id  midterm
0   1       60
1   2       80
2   3       70
3   4       90
4   5       85

In [147]:
test2

   id  final
0   1     70
1   2     83
2   3     65
3   4     95
4   5     80

In [149]:
total = pd.merge(test1, test2, how = "left", on = "id")

In [150]:
total

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [151]:
name = pd.DataFrame(
{
    "nclass": [1, 2, 3, 4, 5], 
    "teacher": ["kim", "lee", "park", "choi", "jung"]

}
)

In [152]:
name

   nclass teacher
0       1     kim
1       2     lee
2       3    park
3       4    choi
4       5    jung

In [154]:
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [158]:
exam_new = pd.merge(exam, name, how = "left", on = "nclass")

In [159]:
exam_new

    id  nclass  math  english  science teacher
0    1       1    50       98       50     kim
1    2       1    60       97       60     kim
2    3       1    45       86       78     kim
3    4       1    30       98       58     kim
4    5       2    25       80       65     lee
5    6       2    50       89       98     lee
6    7       2    80       90       45     lee
7    8       2    90       78       25     lee
8    9       3    20       98       15    park
9   10       3    50       98       45    park
10  11       3    65       65       65    park
11  12       3    45       85       32    park
12  13       4    46       98       65    choi
13  14       4    48       87       12    choi
14  15       4    75       56       78    choi
15  16       4    58       98       65    choi
16  17       5    65       68       98    jung
17  18       5    80       78       90    jung
18  19       5    89       68       87    jung
19  20       5    78       83       58    jung

In [164]:
group_a = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5], 
        "test": [70, 83, 65, 95, 80]
    }
)

group_b = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5],
        "test": [70, 83, 65, 95, 80]
    }
)

In [170]:
pd.concat([group_a,group_b],axis=1)

   id  test  id  test
0   1    70   1    70
1   2    83   2    83
2   3    65   3    65
3   4    95   4    95
4   5    80   5    80

In [174]:
group_all = pd.concat([group_a,group_b])

In [175]:
group_all

   id  test
0   1    70
1   2    83
2   3    65
3   4    95
4   5    80
0   1    70
1   2    83
2   3    65
3   4    95
4   5    80

In [177]:
pd.concat([group_a,group_b])

   id  test
0   1    70
1   2    83
2   3    65
3   4    95
4   5    80
0   1    70
1   2    83
2   3    65
3   4    95
4   5    80